<?php
/**
 * 查看日志数据 - 内容模板
 * @var \Weline\Framework\View\Template $this
 */
?>
<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div>

<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>
                <h4 class='card-title'>
                    <lang>查看数据</lang>
                </h4>
                <p class='card-title-desc'>
                    <lang>查看日志数据</lang>
                </p>
                <pre class='card-text'>{{data}}</pre>
            </div>
        </div>
    </div>
</div>
